#+TITLE:       EGO FTW
#+AUTHOR:      localredhead
#+EMAIL:       localredhead@darchness
#+DATE:        2016-11-25 Fri

#+URI:         /
#+TAGS:        emacs, org-mode
#+DESCRIPTION: The genesis of this site as it is now.

#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

If you're reading this, you're probably very bored.

Previous Setup:
Talk about middleman, and cryogen

- https://github.com/kelvinh/org-page/blob/master/doc/quick-guide.org
- http://kuangdash.github.io/blog/2015/04/15/org-page%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%8E%E4%BD%BF%E7%94%A8/
- http://tumashu.github.io/org-webpage/
- http://emacs-china.github.io/EGO/
- http://emacs-china.github.io/ *

Motivation:
- Evernote is charging for content, and it is only allowed on one device.
- I want to effortlessly publishing my thoughts and content.
- I take notes often.  Google Keep is just an O.K. solution.

Options I considered:
- Nikola https://getnikola.com/
- o-blog http://renard.github.io/o-blog-v2/
- org-page https://github.com/kelvinh/org-page

At first I was intrigued by Nikola.  It looks like a very robust static site generator and it has a large community which I like.  I still found myself drawn to the need to minimize my toolset.  I kept searching because I did not want to have to install this on every machine I wished to blog from.

Then I happened across the listing at http://orgmode.org/worg/org-blog-wiki.html.  It has a nice list of blogging tools, and a few there caught my eye, o-blog and org-page.  The reason why I liked these options was I only needed emacs.  So down the rabbit hole I went.

o-blog was the first, but it frustrated me.  For some reason I happened across the old v1 stuff, and I did not find the v2 stuff before I started writing this post.  Either way the v2 stuff looked equally as useless to me.  Call me a simpleton but I just want a simple numbered list of steps to tell me how to use the software.. I am an software engineer and I do not want to read the source.  The first trait of software engineers is lazyiness.  Never forget thy true self, and shame others who try to make you.  So I took a peak at org-page.

First, org-page seems great, but its sparse in explanation.  I found myself configuring it by error message, eventually solvinging each one to the point that I had a preview of my blog running.

I tried each of the template and they are all very rough, so immediately it is obvious to have success you are going to have to learn how to clone one of these templates and tweak it yourself.  That sounds simple but you then need to get org-page to recognize it.  Spotting several yaks that would need shaving if I took that route I decided to see if I could find any blogs blogging about org-page.

Luck would have it I found one, that lead me to a plethora of emacs knowledge.  The only problem was it was all in Chinese.  Google Translate did the work here, and I eventually came across two other projects that improved upon org-page.

I am having a go with EGO.
